version: '3.1'

services :
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: g4user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbmovie
    volumes: 
      - vpostgresqlmovie:/var/lib/postgresql/data
      
  api:
    build:
      context: .
      args:
        repodir: ${repodir}
        artifact: ${artifact}
        confname: ${confname}
    ports:
      - 8080:8080
      
volumes:
  vpostgresqlmovie: